zuul:
  prefix: /api
  routes:
    server-api:
      path: /server/**
      serviceId: SERVER-API
    client-api:
      path: /client/**
      serviceId: CLIENT-API

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8081

spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000